name: Build and Release

on:
  push:
    tags:
      - 'v*' # Executa quando você criar uma tag como v1.0.3
jobs:
  release:
    runs-on: windows-latest # Build para Windows precisa rodar em Windows

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build Angular
        run: npm run build

      - name: Build and Publish Electron
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token automático do GitHub
        run: npx electron-builder --windows --publish always
